# Generated by Django 6.0.8 on 2026-09-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_changed_at_user_password_changed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_key',
            field=models.CharField(default='default-1', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_type',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
